# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.PositiveIntegerField(default=8634, unique=True),
        ),
    ]
